### ISSUE TITLE
使用938ce75和909ea2b自动构建版本每打开一次应用会使系统界面崩溃一次

### ISSUE THREAD

**Issue by NotWayOut** [GSWXXN/RestoreSplashScreen#34]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.KeyguardIndicationController
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at k5.d.Z(Unknown Source:12)
	at androidx.activity.l.run(Unknown Source:761)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.KeyguardIndicationController
	... 12 more

打开 图标---替换图标获取方式或使用MIUI大图标 会使每次打开应用将系统界面崩溃
关闭上述两个功能后只有打开系统设置（com.android.settings）会使系统界面崩溃

**Comment by GSWXXN** [comment]
看起来和[这里](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/issues/3#issuecomment-1837319082)的错误是一样的, 请试一下关闭 HyperCeiler 的 “锁屏底部显示充电信息” 功能

**Comment by NotWayOut** [comment]
> 看起来和[这里](https://github.com/Xposed-Modules-Repo/com.gswxxn.restoresplashscreen/issues/3#issuecomment-1837319082)的错误是一样的, 请试一下关闭 HyperCeiler 的 “锁屏底部显示充电信息” 功能

可以了，不再崩溃了

**Comment by GSWXXN** [comment]
已经尝试给 HyperCeiler 提交修复了, 请测试一下 HyperCeiler 的最新 canary 版本
